INSERT INTO users (email, username, password) VALUES
('ywxs6479@colorado.edu', 'kkxsiinnmn61', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('aeia6772@colorado.edu', 'pcajicomjg59', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('araw5956@colorado.edu', 'fzqafnxdbx95', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('zczy1418@colorado.edu', 'ceupozicej81', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('xfyo4859@colorado.edu', 'kdhkjiuoaq78', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('cvif7262@colorado.edu', 'fyqnjsgfok00', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('mzrf4363@colorado.edu', 'qkiafygesi49', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('rjzv3749@colorado.edu', 'lxoaytjaik83', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('bysy0938@colorado.edu', 'xqidaawiqn85', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('btks5297@colorado.edu', 'syygnccroh82', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('jkmx7053@colorado.edu', 'xquzcbmiwv59', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('ignm9601@colorado.edu', 'ffnmdhdsoe01', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('kmbt1413@colorado.edu', 'jtbylyfavx12', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('qgku9122@colorado.edu', 'udlnqzxeke91', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('yjez9188@colorado.edu', 'vmfofpbhvs07', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('zjqx0677@colorado.edu', 'gboujofaih75', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('ispt7862@colorado.edu', 'cmsomfyfwn89', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('vbxh4157@colorado.edu', 'gfwzapfazg27', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('emlh7546@colorado.edu', 'jffseajsrr11', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('strc4693@colorado.edu', 'mqthclmwen99', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('xtez7529@colorado.edu', 'ljdrbvlkes94', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('iswz8784@colorado.edu', 'ixkkbxtvoc28', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('elgf8501@colorado.edu', 'akydtfldil29', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('ajpq0026@colorado.edu', 'wnylgxzgrl26', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('xkix5353@colorado.edu', 'mwdyxafzle60', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('gono3481@colorado.edu', 'dlyyjvlnmt95', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('fltg9594@colorado.edu', 'xtlhxccguw35', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('mais9466@colorado.edu', 'nyksqnvxlg87', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('nuzk3026@colorado.edu', 'lkrngqofux68', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('qieh4250@colorado.edu', 'hoyuteyyyv58', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('zyve4201@colorado.edu', 'vrmuyoacko60', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('eklo1660@colorado.edu', 'xagcozldel10', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('ecqd9637@colorado.edu', 'kupirvczqn82', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('dlxa7350@colorado.edu', 'nwladfnhhg74', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('nzwp6196@colorado.edu', 'zkghcdqwan95', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('cjwk6269@colorado.edu', 'htscvabziw58', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('hetp5153@colorado.edu', 'dgfkqatoil07', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('ndlu8069@colorado.edu', 'anzkvfgpvn98', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('gmlw3906@colorado.edu', 'pevqxgngjc01', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('rdjo2026@colorado.edu', 'gtxeyywdof09', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('blli6805@colorado.edu', 'aukbrgubsz56', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('vgpi0362@colorado.edu', 'dcilszpfyb34', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('sbmb9138@colorado.edu', 'yacieoxpua39', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('iydu5515@colorado.edu', 'vhneesthos19', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('hcnl6395@colorado.edu', 'otpmjyukuk26', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('rgqr5105@colorado.edu', 'eqnxhatftt93', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('eifa6842@colorado.edu', 'izkiokmbet68', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('fsjj3370@colorado.edu', 'scrnodlbkc00', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('ikwh9371@colorado.edu', 'igvnlwkddi73', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('rhjk8507@colorado.edu', 'luqiophmkq72', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('przy6061@colorado.edu', 'zxyogyseoc62', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('jbqi1685@colorado.edu', 'phadlnixgl58', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('ncfk4506@colorado.edu', 'uvpiqbiygq73', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('uwfg6223@colorado.edu', 'tyxvbrhzpk89', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('gwki0344@colorado.edu', 'hefanplvno12', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('dhzg8558@colorado.edu', 'adtsuslzvl53', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('jmln3136@colorado.edu', 'dozlryjdvy18', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('qiea6953@colorado.edu', 'glbedwwtao71', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('lige1077@colorado.edu', 'awvifcizal87', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('ayxd5301@colorado.edu', 'kmgywrlmwr16', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('tgxh8779@colorado.edu', 'xmkslrvndu46', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('uuwv1183@colorado.edu', 'ckurpbwcbn34', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('ycft0569@colorado.edu', 'udydzpimwi96', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('uwob6820@colorado.edu', 'aoztekbzhw74', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('evku4569@colorado.edu', 'lwwaetjbmc77', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('rgvl1210@colorado.edu', 'zlvilwszbq22', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('vsxm9239@colorado.edu', 'opausoxwzf88', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('fxxv9629@colorado.edu', 'iyipxsapqc00', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('qfik6005@colorado.edu', 'hzzzemwwui61', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('mskf1343@colorado.edu', 'sqrqcahmmq85', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('ttip4372@colorado.edu', 'ecpkrrrxjp87', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('ummy2004@colorado.edu', 'pyhqteqjgp79', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('jssd0950@colorado.edu', 'kqroclkacy29', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('syil9069@colorado.edu', 'kjzhqpssaj15', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('jsrx7963@colorado.edu', 'yslnlhvvsy37', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('yuip2522@colorado.edu', 'qopjekqbyo19', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('iqbw3275@colorado.edu', 'jthtfnfbda75', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('ithp8268@colorado.edu', 'sahmdrqjyq67', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('scib2404@colorado.edu', 'ieowigdxiz10', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('fsju5150@colorado.edu', 'tejcachovw73', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('sytb1586@colorado.edu', 'kprnexayns23', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('tbdu4134@colorado.edu', 'vstkyvjsoz42', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('vsvm8000@colorado.edu', 'bqobydtrqj04', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('zcpd5259@colorado.edu', 'tiltabdgnh44', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('emzu1864@colorado.edu', 'fxafwotbja52', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('lndr8858@colorado.edu', 'zaghgjnwbq91', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('wjsg6483@colorado.edu', 'dhocwbyiuk46', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('juac9452@colorado.edu', 'doqjhiynnl84', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('fjun9678@colorado.edu', 'vquhpedhjq55', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('eldg6149@colorado.edu', 'aofjjjitvf37', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('bwep9779@colorado.edu', 'dunuxlhisi06', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('fvfn1840@colorado.edu', 'gyyfyifdjw26', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('arut3233@colorado.edu', 'qqomjaeuiv84', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('mdac3303@colorado.edu', 'uxrudisvdg80', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('xftm6002@colorado.edu', 'mnhhwacplg00', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('cdez3270@colorado.edu', 'ylqdvxlpvy55', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('xdgd8493@colorado.edu', 'vicbnuohof09', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('xmbr6665@colorado.edu', 'svvakiymlo63', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('vrbg9796@colorado.edu', 'foxvflbvcc56', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m'),
('rbgx9416@colorado.edu', 'yepyqygfyh42', '$2b$10$HNU.vJ8g8AkHifavzwTw8uQSI.AC2KQ0YjzV4iSJKgflLYjlqux7m');

INSERT INTO ingredients (ingredient_text) VALUES 
('Flour'), ('Sugar'), ('Salt'), ('Pepper'), ('Rice'), ('Pasta'), ('Olive Oil'), ('Vegetable Oil'), 
('Butter'), ('Eggs'), ('Milk'), ('Yogurt'), ('Cheese'), ('Bread'), ('Baking Powder'), ('Baking Soda'), 
('Vanilla Extract'), ('Honey'), ('Maple Syrup'), ('Vinegar'), ('Soy Sauce'), ('Ketchup'), ('Mustard'), 
('Mayonnaise'), ('Tomato Sauce'), ('Canned Tomatoes'), ('Chicken Broth'), ('Beef Broth'), ('Canned Beans'), 
('Canned Tuna'), ('Canned Corn'), ('Canned Chickpeas'), ('Canned Coconut Milk'), ('Peanut Butter'), ('Jam'), 
('Tea'), ('Coffee'), ('Chocolate Chips'), ('Nuts'), ('Dried Fruit'), ('Popcorn'), ('Oats'), ('Cereal'), 
('Peanuts'), ('Cornmeal'), ('Quinoa'), ('Couscous'), ('Barley'), ('Lentils'), ('Chickpea Flour'), 
('Yeast'), ('Cocoa Powder'), ('Almond Flour'), ('Breadcrumbs'), ('Coconut Flakes'), ('Chia Seeds'), 
('Sesame Seeds'), ('Sunflower Seeds'), ('Pumpkin Seeds'), ('Quinoa Flakes'), ('Miso Paste'), ('Tahini'), 
('Worcestershire Sauce'), ('Fish Sauce'), ('Mirin'), ('Ramen Noodles'), ('Rice Noodles'), ('Tortillas'), 
('Wraps'), ('Pita Bread'), ('Dijon Mustard'), ('Sriracha'), ('Tabasco Sauce'), ('Hot Sauce'), ('Pickles'), 
('Olives'), ('Chutney'), ('Marinara Sauce'), ('Salsa'), ('Pesto'), ('Curry Paste'), ('Tomato Paste'), 
('Sour Cream'), ('Cottage Cheese'), ('Ricotta Cheese'), ('Mozzarella Cheese'), ('Feta Cheese'), 
('Parmesan Cheese'), ('Gouda Cheese'), ('Gruyère Cheese'), ('Blue Cheese'), ('Swiss Cheese'), 
('Cheddar Cheese'), ('Monterey Jack Cheese'), ('Provolone Cheese'), ('Goat Cheese'), ('Brie Cheese'), 
('Camembert Cheese'), ('Havarti Cheese'), ('Edam Cheese'), ('Emmental Cheese'), ('Paneer Cheese'), 
('Gorgonzola Cheese'), ('Fontina Cheese'), ('Boursin Cheese'), ('Raspberry Jam'), ('Strawberry Jam'), 
('Peach Jam'), ('Apricot Jam'), ('Plum Jam'), ('Orange Marmalade'), ('Apple Butter'), ('Lemon Curd'), 
('Molasses'), ('Agave Syrup'), ('Raisins'), ('Cranberries'), ('Dates'), ('Pine Nuts'), ('Walnuts'), 
('Pecans'), ('Cashews'), ('Hazelnuts'), ('Macadamia Nuts'), ('Brazil Nuts'), ('Almonds'), ('Coconut Oil'), 
('Sesame Oil'), ('Flaxseed Oil'), ('Pumpkin Seed Oil'), ('Ghee'), ('Coconut Water'), ('Club Soda'), 
('Tonic Water'), ('Ginger Beer'), ('Lime Juice'), ('Lemon Juice'), ('Orange Juice'), ('Apple Juice'), 
('Grape Juice'), ('Pomegranate Juice'), ('Cranberry Juice'), ('Peach Juice'), ('Tomato Juice'), 
('Coconut Water'), ('Raspberry Tea'), ('Mint Tea'), ('Chamomile Tea'), ('Apple Cider Vinegar'), 
('Balsamic Vinegar'), ('Red Wine Vinegar'), ('White Wine Vinegar'), ('Rice Vinegar'), ('Sherry Vinegar'), 
('Malt Vinegar'), ('Coconut Vinegar'), ('Champagne Vinegar'), ('Cane Vinegar'), ('Spirit Vinegar'), 
('Tomato Ketchup'), ('BBQ Sauce'), ('Soy Sauce'), ('Fish Sauce'), ('Worcestershire Sauce'), ('Chili Sauce'), 
('Hoisin Sauce'), ('Oyster Sauce'), ('Tahini'), ('Sriracha'), ('Tabasco Sauce'), ('Mustard'), ('Mayonnaise'), 
('Vegan Mayonnaise'), ('Hot Sauce'), ('Salsa'), ('Guacamole'), ('Pesto'), ('Hummus'), ('Tahini'), 
('Sour Cream'), ('Ranch Dressing'), ('Italian Dressing'), ('French Dressing'), ('Balsamic Vinaigrette'), 
('Caesar Dressing'), ('Thousand Island Dressing'), ('Blue Cheese Dressing'), ('Vinegar'), ('Ground Cinnamon'), ('Ground Ginger'), ('Ground Nutmeg'), ('Ground Cloves'), ('Paprika'), ('Cumin'), 
('Coriander'), ('Turmeric'), ('Bay Leaves'), ('Thyme'), ('Rosemary'), ('Sage'), ('Dill'), 
('Parsley'), ('Mint'), ('Oregano'), ('Basil'), ('Chili Powder'), ('Cayenne Pepper'), ('Red Pepper Flakes'), 
('Curry Powder'), ('Allspice'), ('Star Anise'), ('Cardamom'), ('Saffron'), ('Tarragon'), ('Marjoram'), 
('Ground Black Pepper'), ('Sea Salt'), ('Kosher Salt'), ('Pink Himalayan Salt'), ('Garlic Powder'), 
('Onion Powder'), ('Mustard Seeds'), ('Fennel Seeds'), ('Caraway Seeds'), ('Dried Mixed Herbs'), 
('Celery Salt'), ('Chicken Seasoning'), ('Steak Seasoning'), ('BBQ Spice Mix'), ('Garam Masala'), 
('Chinese Five Spice'), ('Italian Seasoning'), ('Herbes de Provence'), ('Fish Seasoning'), ('Taco Seasoning'), 
('Lemon Pepper Seasoning'), ('Garlic'), ('Onions'), ('Bell Peppers'), ('Tomatoes'), ('Lemons'), 
('Limes'), ('Oranges'), ('Apples'), ('Bananas'), ('Grapes'), ('Strawberries'), ('Blueberries'), 
('Raspberries'), ('Blackberries'), ('Pineapples'), ('Mangoes'), ('Peaches'), ('Plums'), 
('Watermelon'), ('Cantaloupe'), ('Honeydew'), ('Avocado'), ('Cucumber'), ('Zucchini'), 
('Eggplant'), ('Broccoli'), ('Cauliflower'), ('Carrots'), ('Celery'), ('Kale'), ('Spinach'), 
('Romaine Lettuce'), ('Arugula'), ('Spring Mix'), ('Swiss Chard'), ('Collard Greens'), ('Mustard Greens'), 
('Green Beans'), ('Snap Peas'), ('Snow Peas'), ('Asparagus'), ('Brussels Sprouts'), ('Cabbage'), 
('Red Cabbage'), ('Potatoes'), ('Sweet Potatoes'), ('Yams'), ('Butternut Squash'), ('Acorn Squash'), 
('Spaghetti Squash'), ('Pumpkin'), ('Corn'), ('Beets'), ('Radishes'), ('Turnips'), ('Parsnips'), 
('Rutabaga'), ('Jicama'), ('Artichokes'), ('Figs'), ('Dates'), ('Prunes'), ('Raisins'), 
('Currants'), ('Dried Apricots'), ('Dried Cranberries'), ('Sun-Dried Tomatoes'), ('Capers'), 
('Pickled Vegetables'), ('Sauerkraut'), ('Kimchi'), ('Olives'), ('Anchovies'), ('Capers'), 
('Artichoke Hearts'), ('Hearts of Palm'), ('Bamboo Shoots'), ('Water Chestnuts'), ('Baby Corn'), 
('Canned Pumpkin'), ('Canned Pineapple'), ('Canned Peaches'), ('Canned Pears'), ('Canned Mango'), 
('Evaporated Milk'), ('Condensed Milk'), ('Coconut Cream'), ('Almond Butter'), ('Cashew Butter'), 
('Sunflower Seed Butter'), ('Hazelnut Spread'), ('Marmalade'), ('Fruit Preserves'), ('Fruit Compote'), 
('Apple Sauce'), ('Balsamic Glaze'), ('Red Wine'), ('White Wine'), ('Cooking Sherry'), 
('Beer'), ('Vodka'), ('Rum'), ('Whiskey'), ('Tequila'), ('Brandy'), ('Amaretto'), 
('Triple Sec'), ('Vermouth'), ('Marsala Wine'), ('Madeira Wine'), ('Port Wine'), 
('Sake'), ('Mirin'), ('Rice Wine'), ('Coconut Milk Powder'), ('Almond Meal'), ('Ground Flaxseed'), 
('Psyllium Husk'), ('Wheat Bran'), ('Oat Bran'), ('Cornstarch'), ('Tapioca Starch'), 
('Potato Starch'), ('Arrowroot Powder'), ('Xanthan Gum'), ('Guar Gum'), ('Agar Agar'), 
('Gelatin'), ('Pectin'), ('Corn Syrup'), ('Light Corn Syrup'), ('Dark Corn Syrup'), 
('Golden Syrup'), ('Treacle'), ('Sorghum Syrup'), ('Date Syrup'), ('Maple Sugar'), 
('Coconut Sugar'), ('Cane Sugar'), ('Palm Sugar'), ('Demerara Sugar'), ('Turbinado Sugar'), 
('Muscovado Sugar');


INSERT INTO recipes (recipe_name, user_id, recipe_text, is_starred, is_posted) VALUES 
('Garlic Pasta', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\nAliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\nArcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\n', FALSE, TRUE),
('Spicy Tacos', 1, 'Arcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\nAliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\n', FALSE, TRUE),
('Quinoa Salad', 1, 'Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\nArcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\n', FALSE, TRUE),
('Teriyaki Salmon', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\nAliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\nArcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\n', FALSE, TRUE),
('Stuffed Chicken', 1, 'Arcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\nAliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\n', TRUE, TRUE),
('Coconut Curry', 1, 'Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\nArcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\n', FALSE, TRUE),
('Brussels Sprouts', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\nAliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\nArcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\n', TRUE, TRUE),
('Chia Parfait', 1, 'Arcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\nAliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\n', TRUE, TRUE),
('Cajun Skewers', 1, 'Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\nArcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\n', FALSE, TRUE),
('Honey Stir-Fry', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\nAliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\nArcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\n', FALSE, TRUE),
('Garlic Pasta', 2, 'Arcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\nAliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\n', TRUE, TRUE),
('Spicy Tacos', 2, 'Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\nArcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\n', FALSE, TRUE),
('Quinoa Salad', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\nAliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\nArcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\n', FALSE, TRUE),
('Teriyaki Salmon', 2, 'Arcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\nAliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\n', TRUE, TRUE),
('Stuffed Chicken', 2, 'Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\nArcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\n', TRUE, TRUE),
('Coconut Curry', 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\nAliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\nArcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\n', FALSE, TRUE),
('Brussels Sprouts', 2, 'Arcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\nAliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\n', FALSE, TRUE),
('Chia Parfait', 2, 'Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\nArcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\n', FALSE, TRUE),
('Cajun Skewers', 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\nAliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\nArcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\n', TRUE, TRUE),
('Honey Stir-Fry', 3, 'Arcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\nAliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\n', TRUE, TRUE),
('Garlic Pasta', 3, 'Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\nArcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\n', TRUE, TRUE),
('Spicy Tacos', 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\nAliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\nArcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\n', FALSE, TRUE),
('Quinoa Salad', 3, 'Arcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\nAliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\n', TRUE, TRUE),
('Teriyaki Salmon', 3, 'Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\nArcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\n', TRUE, TRUE),
('Stuffed Chicken', 4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\nAliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\nArcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\n', FALSE, TRUE),
('Coconut Curry', 4, 'Arcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\nAliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\n', FALSE, TRUE),
('Brussels Sprouts', 4, 'Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\nArcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\n', FALSE, TRUE),
('Chia Parfait', 4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\nAliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\nArcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\n', TRUE, TRUE),
('Cajun Skewers', 4, 'Arcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\nAliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\n', TRUE, TRUE),
('Honey Stir-Fry', 4, 'Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\nArcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\n', FALSE, TRUE),
('Garlic Pasta', 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\nAliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\nArcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\n', TRUE, TRUE),
('Spicy Tacos', 5, 'Arcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\nAliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\n', TRUE, TRUE),
('Quinoa Salad', 5, 'Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\nArcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\n', TRUE, TRUE),
('Teriyaki Salmon', 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\nAliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\nArcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\n', TRUE, TRUE),
('Stuffed Chicken', 5, 'Arcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\nAliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\n', TRUE, TRUE),
('Coconut Curry', 6, 'Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\nArcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\n', TRUE, TRUE),
('Brussels Sprouts', 6, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\nAliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\nArcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\n', TRUE, TRUE),
('Chia Parfait', 6, 'Arcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\nAliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\n', FALSE, TRUE),
('Cajun Skewers', 6, 'Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\nArcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\n', FALSE, TRUE),
('Honey Stir-Fry', 6, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\nAliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Dapibus ultrices in iaculis nunc sed augue. Pellentesque sit amet porttitor eget dolor morbi non arcu risus.\nArcu odio ut sem nulla pharetra. Iaculis nunc sed augue lacus viverra vitae congue. Nunc consequat interdum varius sit. Egestas fringilla phasellus faucibus scelerisque eleifend.\n', FALSE, TRUE);

INSERT INTO users_to_likes (user_id, recipe_id) VALUES
(53, 8), (18, 35), (88, 7), (33, 1), (34, 18), (15, 32), (85, 27), (25, 37), (18, 18), (4, 1), (52, 21), (33, 10), (67, 40), (15, 20), (44, 34),
(57, 34), (74, 33), (14, 38), (27, 6), (28, 27), (10, 34), (79, 34), (85, 33), (47, 29), (35, 8), (24, 31), (10, 35), (26, 3), (19, 5), (57, 4),
(57, 25), (23, 36), (27, 34), (24, 11), (51, 6), (43, 22), (71, 1), (70, 2), (46, 7), (16, 13), (57, 34), (63, 3), (50, 36), (13, 19), (57, 37),
(68, 39), (32, 18), (63, 17), (85, 6), (50, 2), (32, 4), (68, 20), (69, 37), (85, 38), (86, 30), (32, 20), (65, 12), (84, 26), (79, 15), (90, 25),
(31, 8), (10, 23), (92, 11), (78, 40), (48, 16), (68, 38), (80, 25), (69, 6), (59, 13), (61, 31), (15, 17), (53, 34), (34, 2), (43, 38), (10, 22),
(99, 3), (31, 31), (99, 13), (83, 30), (16, 8), (99, 33), (95, 5), (85, 10), (14, 33), (82, 29), (5, 34), (59, 5), (36, 36), (43, 32), (57, 36),
(86, 38), (36, 23), (7, 1), (84, 3), (10, 37), (68, 33), (7, 27), (66, 1), (11, 20), (84, 20);

